### ISSUE TITLE
hello, I have some problems about "run.sh"

### ISSUE THREAD

**Issue by fornote** [DSIP-UPatras/ICASSP2019_TCN#1]
Every file could be run individually except **"attention_vis.py"** whose traceback was IndexError: list index out of range at line 40, **"RF = int(sys.argv[1])"**. 
           I have already downloaded the Ninapro DB1 data set. And I got the data by runing **"create_dataset.py"** before I ran the **"run.sh"**. However, when I ran the "run.sh", the Pycharm told me that **"ModuleNotFoundError: No module named 'tensorflow'"** in **File "script_experiment.py", line 3**. Because "script_experiment.py" could be run successfully and individually, I didn't know what had I done wrongly. Could you give me some help? thanks.

**Comment by fornote** [comment]
I have solved the second problem by running **"run.sh"** in Terminal instead of Pycharm.

**Comment by ptsinganos** [comment]
For the error in "attention_vis.py" you should run it with two arguments the receptive field (300 or 2500) and the subject id. For example, run: 
`python3 attention_vis.py 300 25`
to visualize the attention weights of the subject 25 for receptive field = 300

**Comment by fornote** [comment]
> For the error in "attention_vis.py" you should run it with two arguments the receptive field (300 or 2500) and the subject id. For example, run:
> `python3 attention_vis.py 300 25`
> to visualize the attention weights of the subject 25 for receptive field = 300

Thanks for your patiently reply. I have solved this problem, but another problem is bothering me. 
After executing `bash run.sh`, 30 epoches of every subject were training finished, and the error, `NameError: name 'MaskedConv1D' id not defined`, occurred. Although there was the error, the coding could still continute to run. If I should loading a pre-training models?
